name: Car Accessories workflow

on:
  push:
    branches: [ main ]
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v2
      
      - name: Step 2 - Set up JDK 1.11
        uses: actions/setup-java@v1
        with: 
         java-version: 1.11

      - name: Step 3 - Build Maven Project
        run: mvn  --batch-mode clean -DskipTests

      - name: Steps 4 - run test cases
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B   jacoco:prepare-agent  verify  org.sonarsource.scanner.maven:sonar-maven-plugin:sonar jacoco:report  -Dsonar.projectKey=SewarAslan_CarAccess
